import 'package:smash_fighters/app/modules/fighters/fighters_module.dart';

final ascendingOrderFighterListMock = [
  FighterEntity(
    objectId: 'fighterObjectId2',
    name: 'A name',
    universe: 'Universo1',
    price: 1,
    popular: null,
    rate: 5,
    downloads: 1,
    description: 'description2',
    createdAt: null,
    imageUrl: 'imageUrl2',
  ),
  FighterEntity(
    objectId: 'fighterObjectId1',
    name: 'B name',
    universe: 'Universo1',
    price: 2,
    popular: null,
    rate: 1,
    downloads: 5,
    description: 'description1',
    createdAt: null,
    imageUrl: 'imageUrl1',
  ),
  FighterEntity(
    objectId: 'fighterObjectId3',
    name: 'C name',
    universe: 'Universo1',
    price: 5,
    popular: null,
    rate: 2,
    downloads: 2,
    description: 'description3',
    createdAt: null,
    imageUrl: 'imageUrl3',
  ),
];
final descendingOrderFighterListMock = [
  FighterEntity(
    objectId: 'fighterObjectId3',
    name: 'C name',
    universe: 'Universo1',
    price: 5,
    popular: null,
    rate: 2,
    downloads: 2,
    description: 'description3',
    createdAt: null,
    imageUrl: 'imageUrl3',
  ),
  FighterEntity(
    objectId: 'fighterObjectId1',
    name: 'B name',
    universe: 'Universo1',
    price: 2,
    popular: null,
    rate: 1,
    downloads: 5,
    description: 'description1',
    createdAt: null,
    imageUrl: 'imageUrl1',
  ),
  FighterEntity(
    objectId: 'fighterObjectId2',
    name: 'A name',
    universe: 'Universo1',
    price: 1,
    popular: null,
    rate: 5,
    downloads: 1,
    description: 'description2',
    createdAt: null,
    imageUrl: 'imageUrl2',
  ),
];
final rateOrderFighterListMock = [
  FighterEntity(
    objectId: 'fighterObjectId1',
    name: 'B name',
    universe: 'Universo1',
    price: 2,
    popular: null,
    rate: 1,
    downloads: 5,
    description: 'description1',
    createdAt: null,
    imageUrl: 'imageUrl1',
  ),
  FighterEntity(
    objectId: 'fighterObjectId3',
    name: 'C name',
    universe: 'Universo1',
    price: 5,
    popular: null,
    rate: 2,
    downloads: 2,
    description: 'description3',
    createdAt: null,
    imageUrl: 'imageUrl3',
  ),
  FighterEntity(
    objectId: 'fighterObjectId2',
    name: 'A name',
    universe: 'Universo1',
    price: 1,
    popular: null,
    rate: 5,
    downloads: 1,
    description: 'description2',
    createdAt: null,
    imageUrl: 'imageUrl2',
  ),
];
final downloadsOrderFighterListMock = [
  FighterEntity(
    objectId: 'fighterObjectId2',
    name: 'A name',
    universe: 'Universo1',
    price: 1,
    popular: null,
    rate: 5,
    downloads: 1,
    description: 'description2',
    createdAt: null,
    imageUrl: 'imageUrl2',
  ),
  FighterEntity(
    objectId: 'fighterObjectId3',
    name: 'C name',
    universe: 'Universo1',
    price: 5,
    popular: null,
    rate: 2,
    downloads: 2,
    description: 'description3',
    createdAt: null,
    imageUrl: 'imageUrl3',
  ),
  FighterEntity(
    objectId: 'fighterObjectId1',
    name: 'B name',
    universe: 'Universo1',
    price: 2,
    popular: null,
    rate: 1,
    downloads: 5,
    description: 'description1',
    createdAt: null,
    imageUrl: 'imageUrl1',
  ),
];
